/* THIS FILE IS AUTOGENERATED - DO NOT EDIT */

#ifndef DEER_REVISION_H
#define DEER_REVISION_H

#define DEER_REVISION "git commit ff7e5fb on 2018-11-20"
#define DEER_VERSION "ff7e5fb"

#endif // DEER_REVISION_H
