/* THIS FILE IS AUTOGENERATED - DO NOT EDIT */

#ifndef DEER_REVISION_H
#define DEER_REVISION_H

#define DEER_REVISION "git commit 4eaf4ef on 2018-12-12"
#define DEER_VERSION "4eaf4ef"

#endif // DEER_REVISION_H
