/* THIS FILE IS AUTOGENERATED - DO NOT EDIT */

#ifndef DEER_REVISION_H
#define DEER_REVISION_H

#define DEER_REVISION "git commit dfdbcb6 on 2019-02-27"
#define DEER_VERSION "dfdbcb6"

#endif // DEER_REVISION_H
