name: tests
on: [push, pull_request]
jobs:
      test-bindings-linux:
            runs-on: ubuntu-latest
            steps:
            - uses: actions/checkout@v2
              with:
                    submodules: recursive
            - name: Setup build system
              run: | 
                  sudo apt update 
                  sudo apt install build-essential cmake libboost-dev libblas-dev liblapack-dev mpich libmpich-dev python3-dev
            - name: Compile neml
              run: |
                  cd neml
                  cmake -DCMAKE_BUILD_TYPE=Release .
                  make -j 2
            - name: Compile extra MOOSE packages
              env:
                    MOOSE_DIR: $GITHUB_WORKSPACE/moose
              run:  |
                  git clone https://github.com/idaholab/moose.git $MOOSE_DIR
                  cd $MOOSE_DIR/scripts
                  export MOOSE_JOBS=2
                  ./update_and_rebuild_petsc.sh
                  ./update_and_rebuild_libmesh.sh
                  ./update_and_rebuild_hit.sh
            - name: Compile code
              env:
                    MOOSE_DIR: $GITHUB_WORKSPACE/moose
              run: |
                    export MOOSE_DIR=$PWD/moose
                    make -j 2 METHOD=opt
            - name: Test code
              env:
                    MOOSE_DIR: $GITHUB_WORKSPACE/moose
                    LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$GITHUB_WORKSPACE/neml/lib
              run: ./run_tests
